import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    ['col','flex flex-col'],
    ['row','flex flex-row'],
    ['center','justify-center items-center'],
    ['rf', 'rounded-full'],
    ['x2', 'h-2 w-2'],
    ['x1', 'h-1 w-1'],
    ['x4', 'h-4 w-4'],
    ['x8', 'h-8 w-8'],
    ['x10', 'h-10 w-10'],
    ['x12', 'h-12 w-12'],
    ['x16', 'h-16 w-16'],
    ['x20', 'h-20 w-20'],
    ['x24', 'h-24 w-24'],
    ['x32', 'h-32 w-32'],
    ['x40', 'h-40 w-40'],
    ['x48', 'h-48 w-48'],
    ['x56', 'h-56 w-56'],
    ['x64', 'h-64 w-64'],
    ['tr', 'top-0 right-0 fixed'],
    ['tl', 'top-0 left-0 fixed'],
    ['bl', 'bottom-0 left-0 fixed'],
    ['br', 'bottom-0 right-0 fixed'],
    ['btn', 'py-2 px-4 rounded'],
    ['cp', 'cursor-pointer'],
    ['shadow','shadow-md shadow-gray-500'],
    ['hover:shadow','hover:shadow-md hover:shadow-gray-500'],
    ['row-start','flex flex-row justify-items-start'],
    ['row-end','flex flex-row justify-items-end'],
    ['row-center','flex flex-row justify-items-center'],
    ['row-between','flex flex-row justify-items-between'],
    ['row-around','flex flex-row justify-items-around'],
    ['col-start','flex flex-col justify-items-start'],
    ['col-end','flex flex-col justify-items-end'],
    ['col-center','flex flex-col justify-items-center'],
    ['col-between','flex flex-col justify-items-between'],
    ['col-around','flex flex-col justify-items-around'],
    ['slide-up','animate-slide-in-up animate-duration-300'],
    ['slide-down','animate-slide-in-down animate-duration-300'],
    ['slide-left','animate-slide-in-left animate-duration-300'],
    ['slide-right','animate-slide-in-right animate-duration-300'],
    ['fade-in','animate-fade-in animate-duration-300'],
    ['fade-in-up','animate-fade-in-up animate-duration-300'],
    ['fade-in-down','animate-fade-in-down animate-duration-300'],
    ['fade-in-left','animate-fade-in-left animate-duration-300'],
    ['fade-in-right','animate-fade-in-right animate-duration-300'],
    ['btn-primary','btn bg-teal hover:brightness-150 hover:outline hover:font-bold hover:underline text-black dark:invert']
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
        script: 'Lobster',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
