// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Badges: typeof import('./components/Badges.vue')['default']
    Blog: typeof import('./components/Blog.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    Code: typeof import('./components/Code.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Email: typeof import('./components/Email.vue')['default']
    Fetch: typeof import('./components/Fetch.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Media: typeof import('./components/Media.vue')['default']
    Mixer: typeof import('./components/Mixer.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    Pdf: typeof import('./components/Pdf.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/Toast.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}

export {}
